name: "HDHive 自动签到"
description: "HDHive 每日签到 + 赌狗签到"
author: "Szt416"

icon: "checkmark.circle.fill"

env_schema:
  HDHIVE_COOKIE:
    name: "HDHive Cookie"
    description: "填写HDHive登录后的完整Cookie"
    default_value: ""

scriptings:
  - http_request:
      name: "HDHive签到"
      match: "^https://hdhive\\.com/$"
      script_url: https://raw.githubusercontent.com/szt416/Rules/refs/heads/main/Surge-Egern/Scripts/HDHive_Signin.js
      timeout: 20

  - cron:
      name: "HDHive每日签到"
      cron: "0 8 * * *"
      script_url: https://raw.githubusercontent.com/szt416/Rules/refs/heads/main/Surge-Egern/Scripts/HDHive_Signin.js

mitm:
  hostnames:
    - hdhive.com
