name: "HDHive 自动签到"
description: "HDHive 每日签到和赌狗签到"
author: "Szt416"

icon: "checkmark.circle.fill"


env_schema:

  HDHIVE_COOKIE:
    name: "HDHive Cookie"
    description: "填写 HDHive 登录后的完整 Cookie"
    default_value: ""


  SIGN_MODE:
    name: "签到模式"
    description: "选择签到方式"
    default_value: "全部签到"
    options:
      - "普通签到"
      - "赌狗签到"
      - "全部签到"


scriptings:

  - cron:
      name: "HDHive签到"
      cron: "0 8 * * *"
      script_url: "https://raw.githubusercontent.com/szt416/Rules/refs/heads/main/Surge-Egern/Module/HDHive_Signin.yaml"
      timeout: 30
